'use strict';

// Electron main process: window + IPC wiring only. Orchestration lives in
// src/checks.js, profile storage in src/gui/profiles.js — both testable
// without Electron.

const { app, BrowserWindow, ipcMain, dialog, shell, safeStorage, Menu } = require('electron');
const path = require('path');
const fs = require('fs');

const { ProfileStore } = require('./profiles');
const { runCheck } = require('../checks');
const ssh = require('../ssh');
const html = require('../report/html');
const markdown = require('../report/markdown');
const { runTrial, runFix } = require('../ci/trial');
const { autoUpdater } = require('electron-updater');

const VERSION = require('../../package.json').version;

let win;
let profiles;

// ------------------------------------------------------------- auto-update --

// Only meaningful in a packaged build (app-update.yml is generated by
// electron-builder from the publish config; it doesn't exist in dev).
function sendUpdateStatus(status) {
  if (win && !win.isDestroyed()) win.webContents.send('update:status', status);
}

function initUpdater() {
  if (!app.isPackaged) return;
  const yml = path.join(process.resourcesPath, 'app-update.yml');
  if (!fs.existsSync(yml)) return;
  autoUpdater.autoDownload = true;
  autoUpdater.on('checking-for-update', () => sendUpdateStatus({ state: 'checking' }));
  autoUpdater.on('update-available', i => sendUpdateStatus({ state: 'available', version: i.version }));
  autoUpdater.on('update-not-available', () => sendUpdateStatus({ state: 'none' }));
  autoUpdater.on('download-progress', p => sendUpdateStatus({ state: 'downloading', percent: Math.round(p.percent) }));
  autoUpdater.on('update-downloaded', i => sendUpdateStatus({ state: 'downloaded', version: i.version }));
  autoUpdater.on('error', () => sendUpdateStatus({ state: 'error' }));
  setTimeout(() => { autoUpdater.checkForUpdates().catch(() => {}); }, 3000);
}

function createWindow() {
  // macOS: removing the whole menu kills the edit-menu roles (Cmd+C/V/Q stop
  // working in inputs). Keep the standard roles there; Windows/Linux get no
  // menu bar at all.
  if (process.platform === 'darwin') {
    Menu.setApplicationMenu(Menu.buildFromTemplate([
      { role: 'appMenu' },
      { role: 'editMenu' },
      { role: 'viewMenu' },
      { role: 'windowMenu' },
    ]));
  }

  // restore size/position from the last session when sane
  let bounds = {};
  try {
    const s = JSON.parse(fs.readFileSync(path.join(app.getPath('userData'), 'window-state.json'), 'utf8'));
    if (s.width >= 940 && s.height >= 620 && s.x > -9000 && s.y > -9000) bounds = { x: s.x, y: s.y, width: s.width, height: s.height };
  } catch { /* first run */ }

  win = new BrowserWindow({
    ...bounds,
    width: bounds.width || 1200,
    height: bounds.height || 800,
    minWidth: 940,
    minHeight: 620,
    title: 'SwitchCheck — 换环境体检',
    backgroundColor: '#f5f6f8',
    show: !process.argv.includes('--smoke'),
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });
  if (process.platform !== 'darwin') win.removeMenu();
  win.loadFile(path.join(__dirname, 'renderer', 'index.html'));

  // remember size/position for the next session
  win.on('close', () => {
    try {
      fs.writeFileSync(path.join(app.getPath('userData'), 'window-state.json'),
        JSON.stringify({ ...win.getBounds(), maximized: win.isMaximized() }));
    } catch { /* best effort */ }
  });

  // --smoke: load the renderer, report, exit. Headless sanity check.
  if (process.argv.includes('--smoke')) {
    win.webContents.on('did-finish-load', () => {
      process.stdout.write('SWITCHCHECK_GUI_SMOKE_OK\n');
      app.quit();
    });
    win.webContents.on('did-fail-load', (_e, code, desc) => {
      process.stderr.write(`smoke failed: ${code} ${desc}\n`);
      app.exit(1);
    });
  }
}

app.whenReady().then(() => {
  profiles = new ProfileStore({ dir: app.getPath('userData'), safeStorage });
  createWindow();
  initUpdater();
});
app.on('window-all-closed', () => app.quit());

// ---------------------------------------------------------------- profiles --

ipcMain.handle('profiles:list', () => ({
  safeStorage: profiles.encryptionAvailable(),
  profiles: profiles.list(),
}));
ipcMain.handle('profiles:save', (_e, input) => profiles.save(input));
ipcMain.handle('profiles:delete', (_e, id) => profiles.delete(id));

ipcMain.handle('profiles:export', async () => {
  const r = await dialog.showSaveDialog(win, {
    defaultPath: 'switchcheck-connections.json',
    filters: [{ name: 'JSON', extensions: ['json'] }],
  });
  if (r.canceled || !r.filePath) return null;
  fs.writeFileSync(r.filePath, JSON.stringify(profiles.exportProfiles(), null, 2));
  return r.filePath;
});

ipcMain.handle('profiles:import', async () => {
  const r = await dialog.showOpenDialog(win, {
    properties: ['openFile'],
    filters: [{ name: 'JSON', extensions: ['json'] }],
  });
  if (r.canceled || !r.filePaths.length) return null;
  const data = JSON.parse(fs.readFileSync(r.filePaths[0], 'utf8'));
  return profiles.importProfiles(data); // { added, skipped }
});

// ------------------------------------------------------------------ checks --

// TOFU: on a successful connect, store the host key fingerprint the first
// time. A later mismatch aborts pre-auth in ssh.js and surfaces as a clear
// error — never silently overwritten here.
function afterConnect(conn, opts) {
  if (opts.profileId && conn.hostFingerprint) {
    profiles.maybeSaveFingerprint(opts.profileId, conn.hostFingerprint);
  }
}

// Lightweight connectivity probe for the connection manager.
ipcMain.handle('ssh:test', async (_e, opts) => {
  try {
    const connOpts = profiles.connectionOpts(opts);
    const conn = await ssh.connect(connOpts);
    try {
      afterConnect(conn, opts);
      const platform = await conn.detectPlatform();
      return { ok: true, platform, fingerprint: conn.hostFingerprint };
    } finally {
      conn.close();
    }
  } catch (e) {
    return { ok: false, error: e.message || String(e) };
  }
});

ipcMain.handle('check:start', (event, opts) => {
  const result = runCheck(opts, {
    send: (stage, message) => {
      if (!event.sender.isDestroyed()) event.sender.send('check:progress', { stage, message, at: Date.now() });
    },
    connectionOpts: o => profiles.connectionOpts(o),
    afterConnect,
  });
  // Persist every completed check so 历史/对比 works across restarts.
  result.then(res => {
    if (res && res.ok) saveHistory(res);
  });
  return result;
});

// ----------------------------------------------------------------- history --

function historyFile() {
  return path.join(app.getPath('userData'), 'history.json');
}

function loadHistory() {
  try {
    const list = JSON.parse(fs.readFileSync(historyFile(), 'utf8'));
    return Array.isArray(list) ? list : [];
  } catch {
    return [];
  }
}

function saveHistory(result) {
  const list = loadHistory();
  list.unshift({
    id: `h_${Date.now()}_${Math.floor(Math.random() * 1e6)}`,
    at: new Date().toISOString(),
    kind: result.kind,
    host: result.host,
    verdict: result.verdict.status,
    counts: result.counts,
    result,
  });
  fs.writeFileSync(historyFile(), JSON.stringify(list.slice(0, 30), null, 2));
}

ipcMain.handle('history:list', () => loadHistory().map(e => ({
  id: e.id, at: e.at, kind: e.kind, host: e.host, verdict: e.verdict, counts: e.counts,
})));

ipcMain.handle('history:get', (_e, id) => {
  const e = loadHistory().find(x => x.id === id);
  return e ? { entry: { id: e.id, at: e.at, kind: e.kind, host: e.host }, result: e.result } : null;
});

ipcMain.handle('history:clear', () => {
  fs.writeFileSync(historyFile(), '[]');
  return { ok: true };
});

// ------------------------------------------------------------------- trial --

// One-click "prove it on 26.04" PR — CLI's --trial, surfaced in the GUI.
ipcMain.handle('trial:run', (event, { ciPath, dryRun }) => {
  const send = m => {
    if (!event.sender.isDestroyed()) event.sender.send('check:progress', { stage: 'trial', message: m, at: Date.now() });
  };
  try {
    const res = runTrial(ciPath, { dryRun: !!dryRun, log: send });
    return res;
  } catch (e) {
    return { ok: false, message: e.message || String(e) };
  }
});

// ----------------------------------------------------------------- dialogs --

ipcMain.handle('dialog:pickFolder', async () => {
  const r = await dialog.showOpenDialog(win, { properties: ['openDirectory'] });
  return r.canceled ? null : r.filePaths[0];
});

ipcMain.handle('dialog:pickKeyFile', async () => {
  const r = await dialog.showOpenDialog(win, {
    properties: ['openFile'],
    filters: [{ name: '所有文件', extensions: ['*'] }],
  });
  return r.canceled ? null : r.filePaths[0];
});

const EXT = { html: '.html', markdown: '.md', json: '.json' };

ipcMain.handle('report:save', async (_e, req) => {
  const r = await dialog.showSaveDialog(win, {
    defaultPath: req.suggestedName + (EXT[req.format] || '.txt'),
    filters: req.format === 'html'
      ? [{ name: '网页报告', extensions: ['html'] }]
      : req.format === 'markdown' ? [{ name: 'Markdown', extensions: ['md'] }] : [{ name: 'JSON', extensions: ['json'] }],
  });
  if (r.canceled || !r.filePath) return null;
  let body;
  // The export speaks the UI's language.
  if (req.format === 'html') body = html.render(req.title, req.sections, req.meta, { lang: req.lang || 'zh' });
  else if (req.format === 'markdown') body = markdown.render(req.title, req.sections, req.meta);
  else body = JSON.stringify({ tool: 'switchcheck', version: VERSION, ...req }, null, 2);
  fs.writeFileSync(r.filePath, body);
  return r.filePath;
});

ipcMain.handle('shell:openExternal', (_e, url) => {
  if (/^https?:\/\//i.test(url)) shell.openExternal(url);
});

ipcMain.handle('app:version', () => VERSION);

// ------------------------------------------------------------------- fix --

// Local counterpart of --trial: rewrite the workflow files in place.
ipcMain.handle('fix:run', (event, { ciPath, dryRun }) => {
  const send = m => {
    if (!event.sender.isDestroyed()) event.sender.send('check:progress', { stage: 'fix', message: m, at: Date.now() });
  };
  try {
    return runFix(ciPath, { dryRun: !!dryRun, log: send });
  } catch (e) {
    return { ok: false, message: e.message || String(e) };
  }
});

// ------------------------------------------------------------------ update --

ipcMain.handle('update:check', () => {
  if (!app.isPackaged) return { state: 'dev' };
  return autoUpdater.checkForUpdates()
    .then(r => ({ state: r && r.updateInfo ? 'available' : 'none', version: r && r.updateInfo ? r.updateInfo.version : null }))
    .catch(e => ({ state: 'error', error: e.message }));
});

ipcMain.handle('update:install', () => {
  if (app.isPackaged) autoUpdater.quitAndInstall();
});
