'use strict';

// Self-contained HTML renderer (inline CSS + a few lines of vanilla JS for
// filtering). Used by `switchcheck linux` — one file, openable anywhere.

const { countByStatus, verdict, sortFindings } = require('../engine');

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
  ));
}

function badge(status) {
  const label = { red: 'blocked', yellow: 'verify', green: 'works', info: 'info' }[status];
  return `<span class="badge b-${status}">${label}</span>`;
}

function render(title, sections, meta = {}) {
  const all = sections.flatMap(s => s.findings);
  const counts = countByStatus(all);
  const v = verdict(all);

  const nav = sections.filter(s => s.findings.length)
    .map(s => `<a href="#sec-${esc(s.id || s.name)}">${esc(s.name)}</a>`).join('');

  const bodyHtml = sections.filter(s => s.findings.length).map(section => {
    const sc = countByStatus(section.findings);
    const head =
      `<h2 id="sec-${esc(section.id || section.name)}">${esc(section.name)} ` +
      `<span class="counts">🔴 ${sc.red} · 🟡 ${sc.yellow} · 🟢 ${sc.green}</span></h2>` +
      `<ul class="items">` +
      sortFindings(section.findings).map(f => {
        const url = f.url ? ` <a class="src" href="${esc(f.url)}" target="_blank" rel="noopener">reference ↗</a>` : '';
        return (
          `<li class="item" data-status="${f.status}">` +
          `${badge(f.status)}<div>` +
          `<div class="t">${esc(f.title)}${url}</div>` +
          (f.detail ? `<div class="d">${esc(f.detail)}</div>` : '') +
          (f.advice ? `<div class="a">→ ${esc(f.advice)}</div>` : '') +
          `</div></li>`
        );
      }).join('') +
      `</ul>`;
    return head;
  }).join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body { font: 15px/1.55 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
         margin: 0 auto; max-width: 880px; padding: 24px 20px 80px; }
  header h1 { font-size: 26px; margin: 0 0 4px; }
  header .meta { opacity: .7; font-size: 13px; }
  nav { display: flex; flex-wrap: wrap; gap: 8px; margin: 18px 0; }
  nav a { text-decoration: none; padding: 4px 10px; border-radius: 999px;
          border: 1px solid color-mix(in srgb, currentColor 25%, transparent); }
  .verdict { padding: 12px 16px; border-radius: 10px; font-weight: 600; margin: 14px 0 6px; }
  .verdict.red { background: #fde8e8; color: #a00; }
  .verdict.yellow { background: #fff4d6; color: #8a6100; }
  .verdict.green { background: #e3f6e3; color: #0a6b0a; }
  .toolbar { margin: 10px 0 0; font-size: 13px; }
  .toolbar button { cursor: pointer; margin-right: 6px; padding: 3px 10px; border-radius: 999px;
                    border: 1px solid color-mix(in srgb, currentColor 30%, transparent);
                    background: transparent; color: inherit; }
  .toolbar button.on { background: color-mix(in srgb, currentColor 15%, transparent); }
  h2 { font-size: 18px; margin: 34px 0 10px; }
  .counts { font-size: 12px; font-weight: 400; opacity: .65; }
  ul.items { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 8px; }
  li.item { display: flex; gap: 10px; padding: 10px 12px; border-radius: 8px;
            border: 1px solid color-mix(in srgb, currentColor 14%, transparent); }
  .badge { flex: none; height: 22px; min-width: 58px; text-align: center; border-radius: 999px;
           font-size: 12px; font-weight: 600; line-height: 22px; text-transform: uppercase; }
  .b-red { background: #fde8e8; color: #b00020; }
  .b-yellow { background: #fff4d6; color: #8a6100; }
  .b-green { background: #e3f6e3; color: #0a6b0a; }
  .b-info { background: #e3ecfd; color: #274f9e; }
  .item .t { font-weight: 600; }
  .item .d { opacity: .8; font-size: 13.5px; }
  .item .a { font-size: 13.5px; margin-top: 2px; }
  .src { font-size: 12px; font-weight: 400; opacity: .7; }
  @media (prefers-color-scheme: dark) {
    .b-red { background: #4a1418; color: #ff9da6; }
    .b-yellow { background: #463a10; color: #ffd670; }
    .b-green { background: #103c1c; color: #8ce99a; }
    .b-info { background: #16294a; color: #91b0f5; }
    .verdict.red { background: #4a1418; color: #ff9da6; }
    .verdict.yellow { background: #463a10; color: #ffd670; }
    .verdict.green { background: #103c1c; color: #8ce99a; }
  }
</style>
</head>
<body>
<header>
  <h1>${esc(title)}</h1>
  <div class="meta">Generated by SwitchCheck${meta.generatedAt ? ' · ' + esc(meta.generatedAt) : ''}${meta.kbDate ? ' · KB snapshot ' + esc(meta.kbDate) : ''}</div>
  <div class="verdict ${v.status}">${esc(v.headline)} — ${counts.red} blocked · ${counts.yellow} verify · ${counts.green} work</div>
  <div class="toolbar">
    Filter:
    <button data-f="all" class="on">all</button>
    <button data-f="red">blocked</button>
    <button data-f="yellow">verify</button>
    <button data-f="green">works</button>
  </div>
  <nav>${nav}</nav>
</header>
${bodyHtml}
<script>
  var buttons = document.querySelectorAll('.toolbar button');
  buttons.forEach(function (b) {
    b.addEventListener('click', function () {
      buttons.forEach(function (x) { x.classList.remove('on'); });
      b.classList.add('on');
      var f = b.dataset.f;
      document.querySelectorAll('li.item').forEach(function (li) {
        li.style.display = (f === 'all' || li.dataset.status === f) ? '' : 'none';
      });
    });
  });
</script>
</body>
</html>
`;
}

module.exports = { render };
