'use strict';

// Markdown renderer — written to a file so it can be dropped into a PR
// description or an issue.

const { countByStatus, verdict, sortFindings } = require('../engine');

function render(title, sections, meta = {}) {
  const out = [`# ${title}`, ''];
  if (meta.generatedAt) out.push(`_Generated by SwitchCheck on ${meta.generatedAt}.${meta.kbDate ? ` Knowledge base snapshot: ${meta.kbDate}.` : ''}_`, '');

  const all = sections.flatMap(s => s.findings);
  const counts = countByStatus(all);
  const v = verdict(all);
  out.push(
    `**Verdict: ${v.headline}** — 🔴 ${counts.red} blocking · 🟡 ${counts.yellow} review · 🟢 ${counts.green} ok · ℹ️ ${counts.info} info`,
    ''
  );

  for (const section of sections) {
    if (!section.findings.length) continue;
    out.push(`## ${section.name}`, '');
    for (const f of sortFindings(section.findings)) {
      const icon = { red: '🔴', yellow: '🟡', green: '🟢', info: 'ℹ️' }[f.status];
      out.push(`- ${icon} **${f.title}**`);
      if (f.detail) out.push(`  - ${f.detail}`);
      if (f.advice) out.push(`  - Fix: ${f.advice}`);
    }
    out.push('');
  }
  return out.join('\n');
}

module.exports = { render };
