'use strict';

// Shared trilingual strings (zh-CN / en / ja) — one source for the Electron
// renderer (via <script>) and the HTML report renderer (via require). UMD on
// purpose. Engine finding text (knowledge-base notes) is English today and
// is NOT part of this table — see docs/ui-design-spec.md roadmap.

(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.SC_LABELS = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  var STR = {
    zh: {
      status: { red: '阻塞', yellow: '需确认', green: '可用', info: '说明' },
      verdict: { red: '未就绪 — 存在阻塞项', yellow: '基本可用 — 有项目需要确认', green: '可以切换' },
      verdictIcon: { red: '🚫', yellow: '⚠️', green: '✅' },
      kind: { linux: 'Windows → Linux 迁移', ci: 'CI → Ubuntu 26.04', runtime: '运行时 EOL' },
      kindIcon: { linux: '🐧', ci: '⚙️', runtime: '⏱️' },
      section: {
        Applications: '应用软件',
        'Steam games': 'Steam 游戏',
        Hardware: '硬件',
        Printers: '打印机',
        'Rollout timeline': '上线时间线',
      },
      ui: {
        tagline: '换环境体检 · 红黄绿报告',
        panelType: '体检类型',
        panelTarget: '体检目标',
        'type.linux': 'Windows → Linux 迁移',
        'type.linux.d': '扫描已装软件、Steam 游戏、硬件、打印机',
        'type.ci': 'CI → Ubuntu 26.04',
        'type.ci.d': '扫描仓库的 GitHub Actions workflows',
        'type.runtime': '运行时 EOL',
        'type.runtime.d': 'Node / Python 版本是否已停维或临期',
        'target.local': '这台电脑',
        'target.sshWin': 'SSH 远程 Windows 主机',
        'target.localRepo': '本地文件夹',
        'target.sshRepo': 'SSH 远程主机上的仓库',
        repoPath: '仓库路径',
        browse: '浏览…',
        remoteRepoPath: '远程仓库路径',
        sshConn: 'SSH 连接',
        manage: '管理…',
        sshPassword: '密码（未保存时需输入）',
        sshPassphrase: '私钥口令（未保存时需输入）',
        sshHintTitle: '远程主机如何启用 OpenSSH 服务器？',
        sshHintBody: '目标 Windows 机器上，管理员 PowerShell 执行：',
        sshHintOr: '或：设置 → 应用 → 可选功能 → 添加「OpenSSH 服务器」。',
        hintLinux: '远程主机需为 Windows 并已启用 OpenSSH 服务器。',
        hintRepo: '远程主机可以是 Windows 或 Linux，通过 SFTP 读取仓库文件。',
        run: '开始体检',
        runCi: '开始 CI 体检',
        runRuntime: '开始运行时体检',
        running: '体检中…',
        progress: '进行中',
        clear: '清除',
        history: '🕘 历史记录',
        themeSystem: '🌗 跟随系统',
        themeLight: '☀️ 浅色',
        themeDark: '🌙 深色',
        emptyTitle: '切换环境之前，先体检一次',
        emptyLead: '结果按 🔴 阻塞 / 🟡 需确认 / 🟢 可用 / ℹ️ 说明 分级，整体结论取最差项。',
        step1: '选择体检类型与目标',
        step2: '一键体检看红黄绿结论',
        step3: '过滤细节，导出报告',
        all: '全部',
        exportHtml: '导出 HTML',
        exportMd: '导出 Markdown',
        exportJson: '导出 JSON',
        trialBtn: '创建试跑 PR',
        trialTitle: '创建一个把 Ubuntu job 钉到 26.04 的分支并开 PR（需要 gh）',
        noFindings: '体检完成 —— 没有发现任何条目。',
        generatedAt: '生成于',
        checkedAt: '体检于',
        kbSnapshot: '知识库快照',
        sshPrefix: 'SSH：',
        reference: '参考 ↗',
        copyTip: '复制这条建议',
        copied: '✓',
        advicePrefix: '建议：',
        managerTitle: 'SSH 连接管理',
        noProfiles: '还没有连接配置。点「＋ 新建连接」添加一台远程主机。',
        newConn: '＋ 新建连接',
        importBtn: '导入…',
        exportBtn: '导出…',
        close: '关闭',
        test: '测试',
        edit: '编辑',
        del: '删除',
        saveConn: '保存连接',
        cancel: '取消',
        fName: '名称',
        fHost: '主机地址',
        fPort: '端口',
        fUser: '用户名',
        fAuth: '认证方式',
        authPassword: '密码',
        authKey: '私钥文件',
        fKeyPath: '私钥文件路径',
        fPassword: '密码',
        fKeyPass: '私钥口令（可选）',
        remember: '把密码/口令加密保存在本机',
        testing: '测试中…',
        testOkWin: '✓ 可连接（Windows）',
        testOkUnix: '✓ 可连接（Linux/Unix）',
        imported: '已导入 {n} 个连接，跳过重复 {s} 个。',
        exported: '已导出（不含密钥）→ {path}',
        delTitle: '删除「{name}」',
        delMsg: '连接配置将被删除，保存在本机的密码/口令也会一并清除。',
        historyTitle: '体检历史',
        clearHistory: '清空历史',
        open: '打开',
        noHistory: '还没有体检记录。跑一次体检后可以在这里回顾和对比。',
        clearHistTitle: '清空体检历史',
        clearHistMsg: '所有历史记录将被删除，且无法恢复。',
        clear: '清空',
        diffHead: '与上次体检（{date}）对比：新增 {n} 项 · 已解决 {m} 项',
        diffNew: '新增：{title}',
        trialConfirmTitle: '创建试跑 PR',
        trialConfirmMsg: '将在仓库中创建一个分支（把 Ubuntu job 钉到 ubuntu-26.04），并尝试通过 gh 打开 PR，让 CI 先用 26.04 试跑。继续吗？',
        trialConfirmOk: '创建 PR',
        errNoProfile: '请先在「SSH 连接」中选择一个连接配置（点「管理…」可新建）。',
        errNoPath: '请填写或选择本地仓库路径。',
        errRun: '体检失败',
        done: '体检完成',
        exportedLine: '已导出：{fmt} → {path}',
        versionFoot: 'SwitchCheck v{v} · 与 CLI 同一体检引擎',
        updateDownloading: '⬇️ 新版本 v{v} 下载中…',
        updatePercent: '⬇️ 下载中 {p}%',
        updateReady: '✅ v{v} 已就绪，点击重启更新',
        updateReadyTip: '不重启也没关系，下次启动时会自动安装',
        langName: '简体中文',
        errNeedProfile: 'errNoProfile',
      },
      stage: {
        connect: '正在连接 {host}:{port} …',
        connected: 'SSH 已连接',
        remoteCollect: '远程采集：{label}…',
        localCollect: '正在采集：{label}…',
        matchLinux: '正在匹配知识库…',
        scanCi: '正在读取 {root} 下的 .github/workflows …',
        matchCi: '正在对照 Ubuntu 26.04 镜像清单…',
        scanRuntime: '正在读取 {root} 下的运行时声明文件 …',
        matchRuntime: '正在对照运行时 EOL 知识库…',
        steps: { software: '已安装软件', steam: 'Steam 库', hardware: '硬件', printers: '打印机' },
      },
    },
    en: {
      status: { red: 'Blocked', yellow: 'Verify', green: 'OK', info: 'Info' },
      verdict: { red: 'Not ready — blocking issues found', yellow: 'Mostly fine — items need review', green: 'Ready to switch' },
      verdictIcon: { red: '🚫', yellow: '⚠️', green: '✅' },
      kind: { linux: 'Windows → Linux migration', ci: 'CI → Ubuntu 26.04', runtime: 'Runtime EOL' },
      kindIcon: { linux: '🐧', ci: '⚙️', runtime: '⏱️' },
      section: {},
      ui: {
        tagline: 'Pre-flight checks · red/yellow/green reports',
        panelType: 'Check type',
        panelTarget: 'Target',
        'type.linux': 'Windows → Linux migration',
        'type.linux.d': 'Scan installed software, Steam games, hardware, printers',
        'type.ci': 'CI → Ubuntu 26.04',
        'type.ci.d': 'Scan the repo’s GitHub Actions workflows',
        'type.runtime': 'Runtime EOL',
        'type.runtime.d': 'Are your Node / Python versions EOL or close?',
        'target.local': 'This computer',
        'target.sshWin': 'SSH remote Windows host',
        'target.localRepo': 'Local folder',
        'target.sshRepo': 'Repo on an SSH host',
        repoPath: 'Repository path',
        browse: 'Browse…',
        remoteRepoPath: 'Remote repository path',
        sshConn: 'SSH connection',
        manage: 'Manage…',
        sshPassword: 'Password (needed if not saved)',
        sshPassphrase: 'Key passphrase (needed if not saved)',
        sshHintTitle: 'How to enable OpenSSH Server on the remote host?',
        sshHintBody: 'On the target Windows machine, run in an admin PowerShell:',
        sshHintOr: 'Or: Settings → Apps → Optional features → add “OpenSSH Server”.',
        hintLinux: 'The remote host must be Windows with OpenSSH Server enabled.',
        hintRepo: 'The remote host can be Windows or Linux — repo files are read over SFTP.',
        run: 'Start check',
        runCi: 'Start CI check',
        runRuntime: 'Start runtime check',
        running: 'Checking…',
        progress: 'In progress',
        clear: 'Clear',
        history: '🕘 History',
        themeSystem: '🌗 System',
        themeLight: '☀️ Light',
        themeDark: '🌙 Dark',
        emptyTitle: 'Check before you switch',
        emptyLead: 'Findings are graded 🔴 blocked / 🟡 verify / 🟢 ok / ℹ️ info; the overall verdict is the worst one.',
        step1: 'Pick a check type and target',
        step2: 'One click for the verdict',
        step3: 'Filter details, export the report',
        all: 'All',
        exportHtml: 'Export HTML',
        exportMd: 'Export Markdown',
        exportJson: 'Export JSON',
        trialBtn: 'Create trial PR',
        trialTitle: 'Creates a branch pinning the Ubuntu jobs to 26.04 and opens a PR (needs gh)',
        noFindings: 'Check finished — nothing to report.',
        generatedAt: 'generated',
        checkedAt: 'checked',
        kbSnapshot: 'KB snapshot',
        sshPrefix: 'SSH:',
        reference: 'reference ↗',
        copyTip: 'Copy this recommendation',
        copied: '✓',
        advicePrefix: 'Advice: ',
        managerTitle: 'SSH connections',
        noProfiles: 'No saved connections yet. Click “＋ New connection” to add a remote host.',
        newConn: '＋ New connection',
        importBtn: 'Import…',
        exportBtn: 'Export…',
        close: 'Close',
        test: 'Test',
        edit: 'Edit',
        del: 'Delete',
        saveConn: 'Save connection',
        cancel: 'Cancel',
        fName: 'Name',
        fHost: 'Host',
        fPort: 'Port',
        fUser: 'Username',
        fAuth: 'Authentication',
        authPassword: 'Password',
        authKey: 'Key file',
        fKeyPath: 'Private key file path',
        fPassword: 'Password',
        fKeyPass: 'Key passphrase (optional)',
        remember: 'Encrypt and store the password/passphrase on this machine',
        testing: 'Testing…',
        testOkWin: '✓ Connected (Windows)',
        testOkUnix: '✓ Connected (Linux/Unix)',
        imported: 'Imported {n} connections, skipped {s} duplicates.',
        exported: 'Exported (no secrets) → {path}',
        delTitle: 'Delete “{name}”',
        delMsg: 'The connection will be removed, along with any password/passphrase stored on this machine.',
        historyTitle: 'Check history',
        clearHistory: 'Clear history',
        open: 'Open',
        noHistory: 'No history yet. Run a check and revisit or compare it here.',
        clearHistTitle: 'Clear check history',
        clearHistMsg: 'All history entries will be deleted. This cannot be undone.',
        clear: 'Clear',
        diffHead: 'Compared with {date}: {n} new · {m} resolved',
        diffNew: 'New: {title}',
        trialConfirmTitle: 'Create trial PR',
        trialConfirmMsg: 'A branch will be created in the repo (pinning the Ubuntu jobs to ubuntu-26.04) and a PR opened via gh, so CI tries 26.04 first. Continue?',
        trialConfirmOk: 'Create PR',
        errNoProfile: 'Pick an SSH connection first (use “Manage…” to create one).',
        errNoPath: 'Choose or enter a local repository path.',
        errRun: 'Check failed',
        done: 'Check finished',
        exportedLine: 'Exported: {fmt} → {path}',
        versionFoot: 'SwitchCheck v{v} · same engine as the CLI',
        updateDownloading: '⬇️ Downloading v{v}…',
        updatePercent: '⬇️ Downloading {p}%',
        updateReady: '✅ v{v} ready — click to restart and update',
        updateReadyTip: 'No rush — the update also installs on next launch',
        langName: 'English',
      },
      stage: {
        connect: 'Connecting to {host}:{port} …',
        connected: 'SSH connected',
        remoteCollect: 'Remote collection: {label}…',
        localCollect: 'Collecting: {label}…',
        matchLinux: 'Matching against the knowledge base…',
        scanCi: 'Reading .github/workflows under {root} …',
        matchCi: 'Comparing against the Ubuntu 26.04 image manifest…',
        scanRuntime: 'Reading runtime declaration files under {root} …',
        matchRuntime: 'Comparing against the runtime EOL knowledge base…',
        steps: { software: 'installed software', steam: 'Steam library', hardware: 'hardware', printers: 'printers' },
      },
    },
    ja: {
      status: { red: 'ブロック', yellow: '要確認', green: 'OK', info: '情報' },
      verdict: { red: '未準備 — ブロック項目あり', yellow: 'ほぼ OK — 要確認の項目あり', green: '切り替え可能' },
      verdictIcon: { red: '🚫', yellow: '⚠️', green: '✅' },
      kind: { linux: 'Windows → Linux 移行', ci: 'CI → Ubuntu 26.04', runtime: 'ランタイム EOL' },
      kindIcon: { linux: '🐧', ci: '⚙️', runtime: '⏱️' },
      section: {},
      ui: {
        tagline: '引っ越し前の事前チェック · 紅黄緑レポート',
        panelType: 'チェック種別',
        panelTarget: 'ターゲット',
        'type.linux': 'Windows → Linux 移行',
        'type.linux.d': 'インストール済みソフト・Steam ゲーム・ハードウェアをスキャン',
        'type.ci': 'CI → Ubuntu 26.04',
        'type.ci.d': 'リポジトリの GitHub Actions workflows をスキャン',
        'type.runtime': 'ランタイム EOL',
        'type.runtime.d': 'Node / Python のバージョンは EOL ではないか',
        'target.local': 'この PC',
        'target.sshWin': 'SSH リモート Windows ホスト',
        'target.localRepo': 'ローカルフォルダ',
        'target.sshRepo': 'SSH ホスト上のリポジトリ',
        repoPath: 'リポジトリパス',
        browse: '参照…',
        remoteRepoPath: 'リモートリポジトリパス',
        sshConn: 'SSH 接続',
        manage: '管理…',
        sshPassword: 'パスワード（未保存時は入力）',
        sshPassphrase: '秘密鍵のパスフレーズ（未保存時は入力）',
        sshHintTitle: 'リモート側で OpenSSH Server を有効にするには？',
        sshHintBody: '対象の Windows マシンで管理者 PowerShell から実行：',
        sshHintOr: 'または：設定 → アプリ → オプション機能 →「OpenSSH サーバー」を追加。',
        hintLinux: 'リモート先は OpenSSH Server が有効な Windows である必要があります。',
        hintRepo: 'リモート先は Windows でも Linux でも OK。リポジトリは SFTP で読み取ります。',
        run: 'チェック開始',
        runCi: 'CI チェック開始',
        runRuntime: 'ランタイムチェック開始',
        running: 'チェック中…',
        progress: '進行中',
        clear: 'クリア',
        history: '🕘 履歴',
        themeSystem: '🌗 システムに従う',
        themeLight: '☀️ ライト',
        themeDark: '🌙 ダーク',
        emptyTitle: '切り替えの前に、一度チェック',
        emptyLead: '結果は 🔴 ブロック / 🟡 要確認 / 🟢 OK / ℹ️ 情報 に分類され、総合判定は最も悪い項目になります。',
        step1: 'チェック種別とターゲットを選ぶ',
        step2: 'ワンクリックで判定を確認',
        step3: 'フィルタして詳細確認、レポート出力',
        all: 'すべて',
        exportHtml: 'HTML 出力',
        exportMd: 'Markdown 出力',
        exportJson: 'JSON 出力',
        trialBtn: 'トライアル PR 作成',
        trialTitle: 'Ubuntu ジョブを 26.04 にピン留めしたブランチを作り PR をオープンします（gh が必要）',
        noFindings: 'チェック完了 —— 報告すべき項目はありません。',
        generatedAt: '生成日',
        checkedAt: 'チェック日',
        kbSnapshot: 'ナレッジベース',
        sshPrefix: 'SSH：',
        reference: '参照 ↗',
        copyTip: 'この推奨をコピー',
        copied: '✓',
        advicePrefix: '推奨：',
        managerTitle: 'SSH 接続の管理',
        noProfiles: '接続設定がまだありません。「＋ 新規接続」から追加してください。',
        newConn: '＋ 新規接続',
        importBtn: 'インポート…',
        exportBtn: 'エクスポート…',
        close: '閉じる',
        test: 'テスト',
        edit: '編集',
        del: '削除',
        saveConn: '接続を保存',
        cancel: 'キャンセル',
        fName: '名前',
        fHost: 'ホスト',
        fPort: 'ポート',
        fUser: 'ユーザー名',
        fAuth: '認証方式',
        authPassword: 'パスワード',
        authKey: '秘密鍵ファイル',
        fKeyPath: '秘密鍵ファイルのパス',
        fPassword: 'パスワード',
        fKeyPass: '秘密鍵のパスフレーズ（任意）',
        remember: 'パスワード/パスフレーズをこの PC で暗号化して保存',
        testing: 'テスト中…',
        testOkWin: '✓ 接続OK（Windows）',
        testOkUnix: '✓ 接続OK（Linux/Unix）',
        imported: '{n} 件をインポート、重複 {s} 件をスキップ。',
        exported: 'エクスポート完了（秘密情報なし）→ {path}',
        delTitle: '「{name}」を削除',
        delMsg: '接続設定を削除します。この PC に保存したパスワード/パスフレーズも一緒に消えます。',
        historyTitle: 'チェック履歴',
        clearHistory: '履歴を消去',
        open: '開く',
        noHistory: '履歴はまだありません。チェックを実行すると、ここから見返せます。',
        clearHistTitle: '履歴を消去',
        clearHistMsg: 'すべての履歴を削除します。元に戻せません。',
        clear: '消去',
        diffHead: '前回（{date}）との比較：新規 {n} 件 · 解決 {m} 件',
        diffNew: '新規：{title}',
        trialConfirmTitle: 'トライアル PR を作成',
        trialConfirmMsg: 'リポジトリにブランチを作成し（Ubuntu ジョブを ubuntu-26.04 にピン留め）、gh 経由で PR をオープンして、CI に 26.04 を試させます。続けますか？',
        trialConfirmOk: 'PR を作成',
        errNoProfile: '先に「SSH 接続」で設定を選んでください（「管理…」から作成できます）。',
        errNoPath: 'ローカルリポジトリのパスを選択または入力してください。',
        errRun: 'チェック失敗',
        done: 'チェック完了',
        exportedLine: 'エクスポート：{fmt} → {path}',
        versionFoot: 'SwitchCheck v{v} · CLI と同じエンジン',
        updateDownloading: '⬇️ v{v} をダウンロード中…',
        updatePercent: '⬇️ ダウンロード中 {p}%',
        updateReady: '✅ v{v} 準備完了 — クリックして再起動・更新',
        updateReadyTip: '急がなくても OK。次回起動時にも自動適用されます',
        langName: '日本語',
      },
      stage: {
        connect: '{host}:{port} に接続中 …',
        connected: 'SSH 接続完了',
        remoteCollect: 'リモート収集：{label}…',
        localCollect: '収集中：{label}…',
        matchLinux: 'ナレッジベースと照合中…',
        scanCi: '{root} の .github/workflows を読み込み中 …',
        matchCi: 'Ubuntu 26.04 イメージマニフェストと照合中…',
        scanRuntime: '{root} のランタイム宣言ファイルを読み込み中 …',
        matchRuntime: 'ランタイム EOL ナレッジベースと照合中…',
        steps: { software: 'インストール済みソフト', steam: 'Steam ライブラリ', hardware: 'ハードウェア', printers: 'プリンター' },
      },
    },
  };

  return {
    LANGS: ['zh', 'en', 'ja'],
    STR: STR,
    // legacy aliases (zh defaults — html.js uses the lang option instead)
    STATUS_ZH: STR.zh.status,
    VERDICT_ZH: STR.zh.verdict,
    VERDICT_ICON: STR.zh.verdictIcon,
    KIND_ZH: STR.zh.kind,
    KIND_ICON: STR.zh.kindIcon,
    SECTION_ZH: STR.zh.section,
  };
});
