'use strict';

// `switchcheck ci --trial`: rewrite Ubuntu runner labels to ubuntu-26.04 on a
// branch and (when `gh` is available) open a PR so CI proves the migration
// before the ubuntu-latest flip lands.

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const { listWorkflowFiles } = require('./scan');
const { loadKb } = require('./check');

const RUNS_ON_RE = /^(\s*runs-on\s*:\s*)ubuntu-(latest|24\.04)\b/gim;
const BRANCH = 'ci/trial-ubuntu-26.04';

function sh(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', ...opts });
  return {
    ok: r.status === 0,
    stdout: (r.stdout || '').trim(),
    stderr: (r.stderr || '').trim(),
  };
}

function toolAvailable(cmd) {
  const probe = process.platform === 'win32' ? spawnSync('where', [cmd], { encoding: 'utf8' }) : sh('command', ['-v', cmd]);
  return probe.status === 0;
}

// Returns [{file, before, after}] for every workflow whose labels change.
function planRewrites(root) {
  return listWorkflowFiles(root)
    .map(rel => {
      const abs = path.join(root, rel);
      const before = fs.readFileSync(abs, 'utf8');
      const after = before.replace(RUNS_ON_RE, '$1ubuntu-26.04');
      return before === after ? null : { rel, abs, before, after };
    })
    .filter(Boolean);
}

function runTrial(root, { dryRun = false, log = () => {} } = {}) {
  const kb = loadKb();
  const rewrites = planRewrites(root);
  if (!rewrites.length) {
    return { ok: false, reason: 'no-change',
      message: 'No ubuntu-latest / ubuntu-24.04 labels found in .github/workflows — nothing to trial.' };
  }

  const summary = rewrites.map(r => `  ${r.rel}`).join('\n');
  log(`Trialing ubuntu-26.04 on:\n${summary}\n`);

  if (dryRun) {
    for (const r of rewrites) {
      const before = r.before.split('\n').filter(l => /runs-on/.test(l)).join(' | ');
      const after = r.after.split('\n').filter(l => /runs-on/.test(l)).join(' | ');
      log(`${r.rel}\n    - ${before}\n    + ${after}`);
    }
    return { ok: true, dryRun: true, rewrites: rewrites.length };
  }

  const repo = sh('git', ['rev-parse', '--show-toplevel'], { cwd: root });
  if (!repo.ok) {
    return { ok: false, reason: 'not-a-repo', message: 'Not a git repository — cannot create a trial branch. Use --dry-run to preview changes.' };
  }
  const remote = sh('git', ['remote'], { cwd: root });

  let branch = BRANCH;
  if (sh('git', ['rev-parse', '--verify', branch], { cwd: root }).ok) {
    branch = `${BRANCH}-${Date.now().toString(36)}`;
  }
  const checkout = sh('git', ['checkout', '-b', branch], { cwd: root });
  if (!checkout.ok) return { ok: false, reason: 'git', message: checkout.stderr || 'git checkout failed' };

  for (const r of rewrites) fs.writeFileSync(r.abs, r.after);
  sh('git', ['add', ...rewrites.map(r => r.rel)], { cwd: root });
  const commitMsg = 'ci: trial ubuntu-26.04 before the ubuntu-latest flip\n\n' +
    `Generated by switchcheck. ubuntu-latest flips to 26.04 between ${kb.latestRollout.phaseStart} and ${kb.latestRollout.completeBy}.`;
  const commit = sh('git', ['commit', '-m', commitMsg], { cwd: root });
  if (!commit.ok) return { ok: false, reason: 'git', message: commit.stderr || 'git commit failed', branch };

  let prUrl = null;
  if (remote.ok && remote.stdout && toolAvailable('gh')) {
    const body = 'Trial run of **ubuntu-26.04** ahead of the ubuntu-latest label flip ' +
      `(${kb.latestRollout.phaseStart} → ${kb.latestRollout.completeBy}).\n\n` +
      'If this build is green, either merge to migrate early, or pin `ubuntu-24.04` and migrate later at your own pace.\n\n' +
      '---\nReport generated by `switchcheck ci --trial`.';
    const pr = sh('gh', ['pr', 'create', '--title', 'CI: trial ubuntu-26.04', '--body', body], { cwd: root });
    if (pr.ok) prUrl = pr.stdout;
  }

  const pushHint = remote.ok && remote.stdout
    ? `  git push -u origin ${branch}\n  gh pr create --title "CI: trial ubuntu-26.04"`
    : '  (no git remote detected — push to your fork once added)';
  return {
    ok: true, branch, prUrl, rewrites: rewrites.length,
    message: prUrl
      ? `Opened PR: ${prUrl}`
      : `Branch ${branch} created and committed.\nTo open the PR manually:\n${pushHint}`,
  };
}

module.exports = { runTrial, planRewrites };
